from __future__ import annotations

from typing import Any, Protocol


class RemoteSessionHandler(Protocol):
    session_id: str | None
    transport: str
    host: str | None
    canonical_host: str | None
    username: str | None
    port: int | None
    created_at: float | None
    last_activity_at: float | None

    def close_session(self) -> None: ...
    def send_input(self, text: str) -> None: ...
    def send_control(self, key: str) -> None: ...
    def resize_session(self, width: int, height: int) -> None: ...
    def read_output(self) -> str: ...
    def flush_output_buffer(self) -> str: ...
    def wait_for_output(self, pattern: str, timeout: float, regex: bool = True, clear_buffer: bool = True) -> dict[str, object]: ...
    def run_command(self, command: str, timeout: float = 30) -> dict[str, object]: ...
    def check_sudo_cache(self, timeout: float = 10) -> dict[str, object]: ...
    def warm_sudo_cache(self, sudo_password: str, timeout: float = 10) -> dict[str, object]: ...
    def clear_sudo_cache(self, timeout: float = 10) -> dict[str, object]: ...
    def upload_file(self, local_path: str, remote_path: str, create_parents: bool = False) -> dict[str, Any]: ...
    def download_file(self, remote_path: str, local_path: str, create_parents: bool = False) -> dict[str, Any]: ...
